
LEVEL_CAPS = {
    "Team Aqua Grunt Petalburg Woods [Boss]": 17,
    "Team Aqua Grunt Museum #2 [Boss]": 21,
    "Leader Brawly [Boss]": 25,
    "Leader Roxanne [Boss]": 32,
    "Trainer Chelle Daycare [Boss]": 35,
    "Leader Wattson [Boss]": 38,
    "Trainer Rival Cycling Road [Boss]": 42,
    "Leader Norman [Boss]": 48,
    "Winstrate Vito Fallarbor [Boss]": 54,
    "Magma Leader Maxie Mt. Chimney [Boss]": 57,
    "Leader Flannery [Double] [Boss]": 65,
    "Aqua Admin Shelly Weather Institute [Boss]": 66,
    "Trainer Rival Bridge [Double] [Boss]": 69,
    "Leader Winona [Boss]": 73,
    "Trainer Rival Lilycove [Boss]": 76,
    "Aqua Leader Archie Mt. Pyre [Tag Battle] [Boss]": 79,
    "Magma Leader Maxie Magma Hideout [Boss]": 81,
    "Aqua Admin Matt [Boss]": 85,
    "Leader Liza [Boss]": 89,
    "Aqua Leader Archie Seafloor Cavern [Boss]": 91,
    "Leader Juan [Double] [Boss]": 95,
    "Winstrate Vito Victory Road [Boss]": 99,
    "Champion Wallace [Boss]": 100
}

PETALBURG_GYM_SAMELEVELS = {
    "Cool Trainer Mary [Accuracy Room]": [1],
    "Cool Trainer Randall [Speed Room]": [-1],
    "Cool Trainer Alexia [Defense Room]": [1,2],
    "Cool Trainer George [Recovery Room]": [-1,1],
    "Cool Trainer Parker [Critical-Hit Room]": [-1,-2],
    "Cool Trainer Jody [Strength Room]": [1],
    "Cool Trainer Berke [Recoil Room]": [-1]
}

TRAINER_RIVAL = {
    "Trainer Rival Cycling Road [Boss]" : [
        {"pokemonTeam": [876,257,230,763,461,869], "itemList": [478,460,472,503,481,452]},
        {"pokemonTeam": [876,260,763,229,701,282], "itemList": [478,553,503,480,452,481]},
        {"pokemonTeam": [876,254,229,230,701,210], "itemList": [478,460,480,522,452,503]},
    ],
    "Trainer Rival Bridge [Double] [Boss]" : [
        {"pokemonTeam": [928,272,373,695,376,9], "itemList": [314,479,348,481,503,472]},
        {"pokemonTeam": [929,130,887,462,454,972], "itemList": [315,479,353,576,481,528]},
            {"pokemonTeam": [927,226,706,958,448,423], "itemList": [313,479,472,481,345,553]},
    ],
    "Trainer Rival Lilycove [Boss]" : [
        {"pokemonTeam": [445,68,461,809,982,928], "itemList": [554,472,479,503,522,314]},
        {"pokemonTeam": [445,65,461,809,983,929], "itemList": [554,481,479,503,528,315]},
        {"pokemonTeam": [445,68,65,809,984,927], "itemList": [554,472,481,503,528,313]},
    ]
}

MOVE_NAMES = ["",
    "Pound",
    "Karate Chop",
    "Double Slap",
    "Comet Punch",
    "Mega Punch",
    "Pay Day",
    "Fire Punch",
    "Ice Punch",
    "Thunder Punch",
    "Scratch",
    "Vise Grip",
    "Guillotine",
    "Razor Wind",
    "Swords Dance",
    "Cut",
    "Gust",
    "Wing Attack",
    "Whirlwind",
    "Fly",
    "Bind",
    "Slam",
    "Vine Whip",
    "Stomp",
    "Double Kick",
    "Mega Kick",
    "Jump Kick",
    "Rolling Kick",
    "Sand Attack",
    "Headbutt",
    "Horn Attack",
    "Fury Attack",
    "Horn Drill",
    "Tackle",
    "Body Slam",
    "Wrap",
    "Take Down",
    "Thrash",
    "Double-Edge",
    "Tail Whip",
    "Poison Sting",
    "Twineedle",
    "Pin Missile",
    "Leer",
    "Bite",
    "Growl",
    "Roar",
    "Sing",
    "Supersonic",
    "Sonic Boom",
    "Disable",
    "Acid",
    "Ember",
    "Flamethrower",
    "Mist",
    "Water Gun",
    "Hydro Pump",
    "Surf",
    "Ice Beam",
    "Blizzard",
    "Psybeam",
    "Bubble Beam",
    "Aurora Beam",
    "Hyper Beam",
    "Peck",
    "Drill Peck",
    "Submission",
    "Low Kick",
    "Counter",
    "Seismic Toss",
    "Strength",
    "Absorb",
    "Mega Drain",
    "Leech Seed",
    "Growth",
    "Razor Leaf",
    "Solar Beam",
    "Poison Powder",
    "Stun Spore",
    "Sleep Powder",
    "Petal Dance",
    "String Shot",
    "Dragon Rage",
    "Fire Spin",
    "Thunder Shock",
    "Thunderbolt",
    "Thunder Wave",
    "Thunder",
    "Rock Throw",
    "Earthquake",
    "Fissure",
    "Dig",
    "Toxic",
    "Confusion",
    "Psychic",
    "Hypnosis",
    "Meditate",
    "Agility",
    "Quick Attack",
    "Rage",
    "Teleport",
    "Night Shade",
    "Mimic",
    "Screech",
    "Double Team",
    "Recover",
    "Harden",
    "Minimize",
    "Smokescreen",
    "Confuse Ray",
    "Withdraw",
    "Defense Curl",
    "Barrier",
    "Light Screen",
    "Haze",
    "Reflect",
    "Focus Energy",
    "Bide",
    "Metronome",
    "Mirror Move",
    "Self-Destruct",
    "Egg Bomb",
    "Lick",
    "Smog",
    "Sludge",
    "Bone Club",
    "Fire Blast",
    "Waterfall",
    "Clamp",
    "Swift",
    "Skull Bash",
    "Spike Cannon",
    "Constrict",
    "Amnesia",
    "Kinesis",
    "Soft Boiled",
    "High Jump Kick",
    "Glare",
    "Dream Eater",
    "Poison Gas",
    "Barrage",
    "Leech Life",
    "Lovely Kiss",
    "Sky Attack",
    "Transform",
    "Bubble",
    "Dizzy Punch",
    "Spore",
    "Flash",
    "Psywave",
    "Splash",
    "Acid Armor",
    "Crabhammer",
    "Explosion",
    "Fury Swipes",
    "Bonemerang",
    "Rest",
    "Rock Slide",
    "Hyper Fang",
    "Sharpen",
    "Conversion",
    "Tri Attack",
    "Super Fang",
    "Slash",
    "Substitute",
    "Struggle",
    "Sketch",
    "Triple Kick",
    "Thief",
    "Spider Web",
    "Mind Reader",
    "Nightmare",
    "Flame Wheel",
    "Snore",
    "Curse",
    "Flail",
    "Conversion 2",
    "Aeroblast",
    "Cotton Spore",
    "Reversal",
    "Spite",
    "Powder Snow",
    "Protect",
    "Mach Punch",
    "Scary Face",
    "Feint Attack",
    "Sweet Kiss",
    "Belly Drum",
    "Sludge Bomb",
    "Mud-Slap",
    "Octazooka",
    "Spikes",
    "Zap Cannon",
    "Foresight",
    "Destiny Bond",
    "Perish Song",
    "Icy Wind",
    "Detect",
    "Bone Rush",
    "Lock-On",
    "Outrage",
    "Sandstorm",
    "Giga Drain",
    "Endure",
    "Charm",
    "Rollout",
    "False Swipe",
    "Swagger",
    "Milk Drink",
    "Spark",
    "Fury Cutter",
    "Steel Wing",
    "Mean Look",
    "Attract",
    "Sleep Talk",
    "Heal Bell",
    "Return",
    "Present",
    "Frustration",
    "Safeguard",
    "Pain Split",
    "Sacred Fire",
    "Magnitude",
    "Dynamic Punch",
    "Megahorn",
    "Dragon Breath",
    "Baton Pass",
    "Encore",
    "Pursuit",
    "Rapid Spin",
    "Sweet Scent",
    "Iron Tail",
    "Metal Claw",
    "Vital Throw",
    "Morning Sun",
    "Synthesis",
    "Moonlight",
    "Hidden Power",
    "Cross Chop",
    "Twister",
    "Rain Dance",
    "Sunny Day",
    "Crunch",
    "Mirror Coat",
    "Psych Up",
    "Extreme Speed",
    "Ancient Power",
    "Shadow Ball",
    "Future Sight",
    "Rock Smash",
    "Whirlpool",
    "Beat Up",
    "Fake Out",
    "Uproar",
    "Stockpile",
    "Spit Up",
    "Swallow",
    "Heat Wave",
    "Hail",
    "Torment",
    "Flatter",
    "Will-O-Wisp",
    "Memento",
    "Facade",
    "Focus Punch",
    "Smelling Salts",
    "Follow Me",
    "Nature Power",
    "Charge",
    "Taunt",
    "Helping Hand",
    "Trick",
    "Role Play",
    "Wish",
    "Assist",
    "Ingrain",
    "Superpower",
    "Magic Coat",
    "Recycle",
    "Revenge",
    "Brick Break",
    "Yawn",
    "Knock Off",
    "Endeavor",
    "Eruption",
    "Skill Swap",
    "Imprison",
    "Refresh",
    "Grudge",
    "Snatch",
    "Secret Power",
    "Dive",
    "Arm Thrust",
    "Camouflage",
    "Tail Glow",
    "Luster Purge",
    "Mist Ball",
    "Feather Dance",
    "Teeter Dance",
    "Blaze Kick",
    "Mud Sport",
    "Ice Ball",
    "Needle Arm",
    "Slack Off",
    "Hyper Voice",
    "Poison Fang",
    "Crush Claw",
    "Blast Burn",
    "Hydro Cannon",
    "Meteor Mash",
    "Astonish",
    "Weather Ball",
    "Aromatherapy",
    "Fake Tears",
    "Air Cutter",
    "Overheat",
    "Odor Sleuth",
    "Rock Tomb",
    "Silver Wind",
    "Metal Sound",
    "Grass Whistle",
    "Tickle",
    "Cosmic Power",
    "Water Spout",
    "Signal Beam",
    "Shadow Punch",
    "Extrasensory",
    "Sky Uppercut",
    "Sand Tomb",
    "Sheer Cold",
    "Muddy Water",
    "Bullet Seed",
    "Aerial Ace",
    "Icicle Spear",
    "Iron Defense",
    "Block",
    "Howl",
    "Dragon Claw",
    "Frenzy Plant",
    "Bulk Up",
    "Bounce",
    "Mud Shot",
    "Poison Tail",
    "Covet",
    "Volt Tackle",
    "Magical Leaf",
    "Water Sport",
    "Calm Mind",
    "Leaf Blade",
    "Dragon Dance",
    "Rock Blast",
    "Shock Wave",
    "Water Pulse",
    "Doom Desire",
    "Psycho Boost",
    "Roost",
    "Gravity",
    "Miracle Eye",
    "Wake-Up Slap",
    "Hammer Arm",
    "Gyro Ball",
    "Healing Wish",
    "Brine",
    "Natural Gift",
    "Feint",
    "Pluck",
    "Tailwind",
    "Acupressure",
    "Metal Burst",
    "U-turn",
    "Close Combat",
    "Payback",
    "Assurance",
    "Embargo",
    "Fling",
    "Psycho Shift",
    "Trump Card",
    "Heal Block",
    "Wring Out",
    "Power Trick",
    "Gastro Acid",
    "Lucky Chant",
    "Me First",
    "Copycat",
    "Power Swap",
    "Guard Swap",
    "Punishment",
    "Last Resort",
    "Worry Seed",
    "Sucker Punch",
    "Toxic Spikes",
    "Heart Swap",
    "Aqua Ring",
    "Magnet Rise",
    "Flare Blitz",
    "Force Palm",
    "Aura Sphere",
    "Rock Polish",
    "Poison Jab",
    "Dark Pulse",
    "Night Slash",
    "Aqua Tail",
    "Seed Bomb",
    "Air Slash",
    "X-Scissor",
    "Bug Buzz",
    "Dragon Pulse",
    "Dragon Rush",
    "Power Gem",
    "Drain Punch",
    "Vacuum Wave",
    "Focus Blast",
    "Energy Ball",
    "Brave Bird",
    "Earth Power",
    "Switcheroo",
    "Giga Impact",
    "Nasty Plot",
    "Bullet Punch",
    "Avalanche",
    "Ice Shard",
    "Shadow Claw",
    "Thunder Fang",
    "Ice Fang",
    "Fire Fang",
    "Shadow Sneak",
    "Mud Bomb",
    "Psycho Cut",
    "Zen Headbutt",
    "Mirror Shot",
    "Flash Cannon",
    "Rock Climb",
    "Defog",
    "Trick Room",
    "Draco Meteor",
    "Discharge",
    "Lava Plume",
    "Leaf Storm",
    "Power Whip",
    "Rock Wrecker",
    "Cross Poison",
    "Gunk Shot",
    "Iron Head",
    "Magnet Bomb",
    "Stone Edge",
    "Captivate",
    "Stealth Rock",
    "Grass Knot",
    "Chatter",
    "Judgment",
    "Bug Bite",
    "Charge Beam",
    "Wood Hammer",
    "Aqua Jet",
    "Attack Order",
    "Defend Order",
    "Heal Order",
    "Head Smash",
    "Double Hit",
    "Roar of Time",
    "Spacial Rend",
    "Lunar Dance",
    "Crush Grip",
    "Magma Storm",
    "Dark Void",
    "Seed Flare",
    "Ominous Wind",
    "Shadow Force",
    "Hone Claws",
    "Wide Guard",
    "Guard Split",
    "Power Split",
    "Wonder Room",
    "Psyshock",
    "Venoshock",
    "Autotomize",
    "Rage Powder",
    "Telekinesis",
    "Magic Room",
    "Smack Down",
    "Storm Throw",
    "Flame Burst",
    "Sludge Wave",
    "Quiver Dance",
    "Heavy Slam",
    "Synchronoise",
    "Electro Ball",
    "Soak",
    "Flame Charge",
    "Coil",
    "Low Sweep",
    "Acid Spray",
    "Foul Play",
    "Simple Beam",
    "Entrainment",
    "After You",
    "Round",
    "Echoed Voice",
    "Chip Away",
    "Clear Smog",
    "Stored Power",
    "Quick Guard",
    "Ally Switch",
    "Scald",
    "Shell Smash",
    "Heal Pulse",
    "Hex",
    "Sky Drop",
    "Shift Gear",
    "Circle Throw",
    "Incinerate",
    "Quash",
    "Acrobatics",
    "Reflect Type",
    "Retaliate",
    "Final Gambit",
    "Bestow",
    "Inferno",
    "Water Pledge",
    "Fire Pledge",
    "Grass Pledge",
    "Volt Switch",
    "Struggle Bug",
    "Bulldoze",
    "Frost Breath",
    "Dragon Tail",
    "Work Up",
    "Electroweb",
    "Wild Charge",
    "Drill Run",
    "Dual Chop",
    "Heart Stamp",
    "Horn Leech",
    "Sacred Sword",
    "Razor Shell",
    "Heat Crash",
    "Leaf Tornado",
    "Steamroller",
    "Cotton Guard",
    "Night Daze",
    "Psystrike",
    "Tail Slap",
    "Hurricane",
    "Head Charge",
    "Gear Grind",
    "Searing Shot",
    "Techno Blast",
    "Relic Song",
    "Secret Sword",
    "Glaciate",
    "Bolt Strike",
    "Blue Flare",
    "Fiery Dance",
    "Freeze Shock",
    "Ice Burn",
    "Snarl",
    "Icicle Crash",
    "V-create",
    "Fusion Flare",
    "Fusion Bolt",
    "Flying Press",
    "Mat Block",
    "Belch",
    "Rototiller",
    "Sticky Web",
    "Fell Stinger",
    "Phantom Force",
    "Trick-or-Treat",
    "Noble Roar",
    "Ion Deluge",
    "Parabolic Charge",
    "Forest's Curse",
    "Petal Blizzard",
    "Freeze-Dry",
    "Disarming Voice",
    "Parting Shot",
    "Topsy-Turvy",
    "Draining Kiss",
    "Crafty Shield",
    "Flower Shield",
    "Grassy Terrain",
    "Misty Terrain",
    "Electrify",
    "Play Rough",
    "Fairy Wind",
    "Moonblast",
    "Boomburst",
    "Fairy Lock",
    "King's Shield",
    "Play Nice",
    "Confide",
    "Diamond Storm",
    "Steam Eruption",
    "Hyperspace Hole",
    "Water Shuriken",
    "Mystical Fire",
    "Spiky Shield",
    "Aromatic Mist",
    "Eerie Impulse",
    "Venom Drench",
    "Powder",
    "Geomancy",
    "Magnetic Flux",
    "Happy Hour",
    "Electric Terrain",
    "Dazzling Gleam",
    "Celebrate",
    "Hold Hands",
    "Baby-Doll Eyes",
    "Nuzzle",
    "Hold Back",
    "Infestation",
    "Power-Up Punch",
    "Oblivion Wing",
    "Thousand Arrows",
    "Thousand Waves",
    "Land's Wrath",
    "Light of Ruin",
    "Origin Pulse",
    "Precipice Blades",
    "Dragon Ascent",
    "Hyperspace Fury",
    "Shore Up",
    "First Impression",
    "Baneful Bunker",
    "Spirit Shackle",
    "Darkest Lariat",
    "Sparkling Aria",
    "Ice Hammer",
    "Floral Healing",
    "High Horsepower",
    "Strength Sap",
    "Solar Blade",
    "Leafage",
    "Spotlight",
    "Toxic Thread",
    "Laser Focus",
    "Gear Up",
    "Throat Chop",
    "Pollen Puff",
    "Anchor Shot",
    "Psychic Terrain",
    "Lunge",
    "Fire Lash",
    "Power Trip",
    "Burn Up",
    "Speed Swap",
    "Smart Strike",
    "Purify",
    "Revelation Dance",
    "Core Enforcer",
    "Trop Kick",
    "Instruct",
    "Beak Blast",
    "Clanging Scales",
    "Dragon Hammer",
    "Brutal Swing",
    "Aurora Veil",
    "Shell Trap",
    "Fleur Cannon",
    "Psychic Fangs",
    "Stomping Tantrum",
    "Shadow Bone",
    "Accelerock",
    "Liquidation",
    "Prismatic Laser",
    "Spectral Thief",
    "Sunsteel Strike",
    "Moongeist Beam",
    "Tearful Look",
    "Zing Zap",
    "Nature's Madness",
    "Multi-Attack",
    "Mind Blown",
    "Plasma Fists",
    "Photon Geyser",
    "Zippy Zap",
    "Splishy Splash",
    "Floaty Fall",
    "Pika Papow",
    "Bouncy Bubble",
    "Buzzy Buzz",
    "Sizzly Slide",
    "Glitzy Glow",
    "Baddy Bad",
    "Sappy Seed",
    "Freezy Frost",
    "Sparkly Swirl",
    "Veevee Volley",
    "Double Iron Bash",
    "Dynamax Cannon",
    "Snipe Shot",
    "Jaw Lock",
    "Stuff Cheeks",
    "No Retreat",
    "Tar Shot",
    "Magic Powder",
    "Dragon Darts",
    "Teatime",
    "Octolock",
    "Bolt Beak",
    "Fishious Rend",
    "Court Change",
    "Clangorous Soul",
    "Body Press",
    "Decorate",
    "Drum Beating",
    "Snap Trap",
    "Pyro Ball",
    "Behemoth Blade",
    "Behemoth Bash",
    "Aura Wheel",
    "Breaking Swipe",
    "Branch Poke",
    "Overdrive",
    "Apple Acid",
    "Grav Apple",
    "Spirit Break",
    "Strange Steam",
    "Life Dew",
    "Obstruct",
    "False Surrender",
    "Meteor Assault",
    "Eternabeam",
    "Steel Beam",
    "Expanding Force",
    "Steel Roller",
    "Scale Shot",
    "Meteor Beam",
    "Shell Side Arm",
    "Misty Explosion",
    "Grassy Glide",
    "Rising Voltage",
    "Terrain Pulse",
    "Skitter Smack",
    "Burning Jealousy",
    "Lash Out",
    "Poltergeist",
    "Corrosive Gas",
    "Coaching",
    "Flip Turn",
    "Triple Axel",
    "Dual Wingbeat",
    "Scorching Sands",
    "Jungle Healing",
    "Wicked Blow",
    "Surging Strikes",
    "Thunder Cage",
    "Dragon Energy",
    "Freezing Glare",
    "Fiery Wrath",
    "Thunderous Kick",
    "Glacial Lance",
    "Astral Barrage",
    "Eerie Spell",
    "Dire Claw",
    "Psyshield Bash",
    "Power Shift",
    "Stone Axe",
    "Springtide Storm",
    "Mystical Power",
    "Raging Fury",
    "Wave Crash",
    "Chloroblast",
    "Mountain Gale",
    "Victory Dance",
    "Headlong Rush",
    "Barb Barrage",
    "Esper Wing",
    "Bitter Malice",
    "Shelter",
    "Triple Arrows",
    "Infernal Parade",
    "Ceaseless Edge",
    "Bleakwind Storm",
    "Wildbolt Storm",
    "Sandsear Storm",
    "Lunar Blessing",
    "Take Heart"
]

POKEMON_NAMES = ["",
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran-F",
    "Nidorina",
    "Nidoqueen",
    "Nidoran-M",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch’d",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Wormadam",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Shellos",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
    "Victini",
    "Snivy",
    "Servine",
    "Serperior",
    "Tepig",
    "Pignite",
    "Emboar",
    "Oshawott",
    "Dewott",
    "Samurott",
    "Patrat",
    "Watchog",
    "Lillipup",
    "Herdier",
    "Stoutland",
    "Purrloin",
    "Liepard",
    "Pansage",
    "Simisage",
    "Pansear",
    "Simisear",
    "Panpour",
    "Simipour",
    "Munna",
    "Musharna",
    "Pidove",
    "Tranquill",
    "Unfezant",
    "Blitzle",
    "Zebstrika",
    "Roggenrola",
    "Boldore",
    "Gigalith",
    "Woobat",
    "Swoobat",
    "Drilbur",
    "Excadrill",
    "Audino",
    "Timburr",
    "Gurdurr",
    "Conkeldurr",
    "Tympole",
    "Palpitoad",
    "Seismitoad",
    "Throh",
    "Sawk",
    "Sewaddle",
    "Swadloon",
    "Leavanny",
    "Venipede",
    "Whirlipede",
    "Scolipede",
    "Cottonee",
    "Whimsicott",
    "Petilil",
    "Lilligant",
    "Basculin",
    "Sandile",
    "Krokorok",
    "Krookodile",
    "Darumaka",
    "Darmanitan",
    "Maractus",
    "Dwebble",
    "Crustle",
    "Scraggy",
    "Scrafty",
    "Sigilyph",
    "Yamask",
    "Cofagrigus",
    "Tirtouga",
    "Carracosta",
    "Archen",
    "Archeops",
    "Trubbish",
    "Garbodor",
    "Zorua",
    "Zoroark",
    "Minccino",
    "Cinccino",
    "Gothita",
    "Gothorita",
    "Gothitelle",
    "Solosis",
    "Duosion",
    "Reuniclus",
    "Ducklett",
    "Swanna",
    "Vanillite",
    "Vanillish",
    "Vanilluxe",
    "Deerling",
    "Sawsbuck",
    "Emolga",
    "Karrablast",
    "Escavalier",
    "Foongus",
    "Amoonguss",
    "Frillish",
    "Jellicent",
    "Alomomola",
    "Joltik",
    "Galvantula",
    "Ferroseed",
    "Ferrothorn",
    "Klink",
    "Klang",
    "Klinklang",
    "Tynamo",
    "Eelektrik",
    "Eelektross",
    "Elgyem",
    "Beheeyem",
    "Litwick",
    "Lampent",
    "Chandelure",
    "Axew",
    "Fraxure",
    "Haxorus",
    "Cubchoo",
    "Beartic",
    "Cryogonal",
    "Shelmet",
    "Accelgor",
    "Stunfisk",
    "Mienfoo",
    "Mienshao",
    "Druddigon",
    "Golett",
    "Golurk",
    "Pawniard",
    "Bisharp",
    "Bouffalant",
    "Rufflet",
    "Braviary",
    "Vullaby",
    "Mandibuzz",
    "Heatmor",
    "Durant",
    "Deino",
    "Zweilous",
    "Hydreigon",
    "Larvesta",
    "Volcarona",
    "Cobalion",
    "Terrakion",
    "Virizion",
    "Tornadus",
    "Thundurus",
    "Reshiram",
    "Zekrom",
    "Landorus",
    "Kyurem",
    "Keldeo",
    "Meloetta",
    "Genesect",
    "Chespin",
    "Quilladin",
    "Chesnaught",
    "Fennekin",
    "Braixen",
    "Delphox",
    "Froakie",
    "Frogadier",
    "Greninja",
    "Bunnelby",
    "Diggersby",
    "Fletchling",
    "Fletchinder",
    "Talonflame",
    "Scatterbug",
    "Spewpa",
    "Vivillon",
    "Litleo",
    "Pyroar",
    "Flabébé",
    "Floette",
    "Florges",
    "Skiddo",
    "Gogoat",
    "Pancham",
    "Pangoro",
    "Furfrou",
    "Espurr",
    "Meowstic",
    "Honedge",
    "Doublade",
    "Aegislash-Both",
    "Spritzee",
    "Aromatisse",
    "Swirlix",
    "Slurpuff",
    "Inkay",
    "Malamar",
    "Binacle",
    "Barbaracle",
    "Skrelp",
    "Dragalge",
    "Clauncher",
    "Clawitzer",
    "Helioptile",
    "Heliolisk",
    "Tyrunt",
    "Tyrantrum",
    "Amaura",
    "Aurorus",
    "Sylveon",
    "Hawlucha",
    "Dedenne",
    "Carbink",
    "Goomy",
    "Sliggoo",
    "Goodra",
    "Klefki",
    "Phantump",
    "Trevenant",
    "Pumpkaboo",
    "Gourgeist",
    "Bergmite",
    "Avalugg",
    "Noibat",
    "Noivern",
    "Xerneas",
    "Yveltal",
    "Zygarde",
    "Diancie",
    "Hoopa",
    "Volcanion",
    "Rowlet",
    "Dartrix",
    "Decidueye",
    "Litten",
    "Torracat",
    "Incineroar",
    "Popplio",
    "Brionne",
    "Primarina",
    "Pikipek",
    "Trumbeak",
    "Toucannon",
    "Yungoos",
    "Gumshoos",
    "Grubbin",
    "Charjabug",
    "Vikavolt",
    "Crabrawler",
    "Crabominable",
    "Oricorio",
    "Cutiefly",
    "Ribombee",
    "Rockruff",
    "Lycanroc",
    "Wishiwashi",
    "Mareanie",
    "Toxapex",
    "Mudbray",
    "Mudsdale",
    "Dewpider",
    "Araquanid",
    "Fomantis",
    "Lurantis",
    "Morelull",
    "Shiinotic",
    "Salandit",
    "Salazzle",
    "Stufful",
    "Bewear",
    "Bounsweet",
    "Steenee",
    "Tsareena",
    "Comfey",
    "Oranguru",
    "Passimian",
    "Wimpod",
    "Golisopod",
    "Sandygast",
    "Palossand",
    "Pyukumuku",
    "Type: Null",
    "Silvally",
    "Minior",
    "Komala",
    "Turtonator",
    "Togedemaru",
    "Mimikyu",
    "Bruxish",
    "Drampa",
    "Dhelmise",
    "Jangmo-o",
    "Hakamo-o",
    "Kommo-o",
    "Tapu Koko",
    "Tapu Lele",
    "Tapu Bulu",
    "Tapu Fini",
    "Cosmog",
    "Cosmoem",
    "Solgaleo",
    "Lunala",
    "Nihilego",
    "Buzzwole",
    "Pheromosa",
    "Xurkitree",
    "Celesteela",
    "Kartana",
    "Guzzlord",
    "Necrozma",
    "Magearna",
    "Marshadow",
    "Poipole",
    "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Zeraora",
    "Meltan",
    "Melmetal",
    "Grookey",
    "Thwackey",
    "Rillaboom",
    "Scorbunny",
    "Raboot",
    "Cinderace",
    "Sobble",
    "Drizzile",
    "Inteleon",
    "Skwovet",
    "Greedent",
    "Rookidee",
    "Corvisquire",
    "Corviknight",
    "Blipbug",
    "Dottler",
    "Orbeetle",
    "Nickit",
    "Thievul",
    "Gossifleur",
    "Eldegoss",
    "Wooloo",
    "Dubwool",
    "Chewtle",
    "Drednaw",
    "Yamper",
    "Boltund",
    "Rolycoly",
    "Carkol",
    "Coalossal",
    "Applin",
    "Flapple",
    "Appletun",
    "Silicobra",
    "Sandaconda",
    "Cramorant",
    "Arrokuda",
    "Barraskewda",
    "Toxel",
    "Toxtricity",
    "Sizzlipede",
    "Centiskorch",
    "Clobbopus",
    "Grapploct",
    "Sinistea",
    "Polteageist",
    "Hatenna",
    "Hattrem",
    "Hatterene",
    "Impidimp",
    "Morgrem",
    "Grimmsnarl",
    "Obstagoon",
    "Perrserker",
    "Cursola",
    "Sirfetch’d",
    "Mr. Rime",
    "Runerigus",
    "Milcery",
    "Alcremie",
    "Falinks",
    "Pincurchin",
    "Snom",
    "Frosmoth",
    "Stonjourner",
    "Eiscue",
    "Indeedee",
    "Morpeko",
    "Cufant",
    "Copperajah",
    "Dracozolt",
    "Arctozolt",
    "Dracovish",
    "Arctovish",
    "Duraludon",
    "Dreepy",
    "Drakloak",
    "Dragapult",
    "Zacian",
    "Zamazenta",
    "Eternatus",
    "Kubfu",
    "Urshifu",
    "Zarude",
    "Regieleki",
    "Regidrago",
    "Glastrier",
    "Spectrier",
    "Calyrex",
    "Wyrdeer",
    "Kleavor",
    "Ursaluna",
    "Basculegion",
    "Sneasler",
    "Overqwil",
    "Enamorus",
    "Venusaur-Mega",
    "Charizard-Mega-X",
    "Charizard-Mega-Y",
    "Blastoise-Mega",
    "Beedrill-Mega",
    "Pidgeot-Mega",
    "Alakazam-Mega",
    "Slowbro-Mega",
    "Gengar-Mega",
    "Kangaskhan-Mega",
    "Pinsir-Mega",
    "Gyarados-Mega",
    "Aerodactyl-Mega",
    "Mewtwo-Mega-X",
    "Mewtwo-Mega-Y",
    "Ampharos-Mega",
    "Steelix-Mega",
    "Scizor-Mega",
    "Heracross-Mega",
    "Houndoom-Mega",
    "Tyranitar-Mega",
    "Sceptile-Mega",
    "Blaziken-Mega",
    "Swampert-Mega",
    "Gardevoir-Mega",
    "Sableye-Mega",
    "Mawile-Mega",
    "Aggron-Mega",
    "Medicham-Mega",
    "Manectric-Mega",
    "Sharpedo-Mega",
    "Camerupt-Mega",
    "Altaria-Mega",
    "Banette-Mega",
    "Absol-Mega",
    "Glalie-Mega",
    "Salamence-Mega",
    "Metagross-Mega",
    "Latias-Mega",
    "Latios-Mega",
    "Lopunny-Mega",
    "Garchomp-Mega",
    "Lucario-Mega",
    "Abomasnow-Mega",
    "Gallade-Mega",
    "Audino-Mega",
    "Diancie-Mega",
    "Rayquaza-Mega",
    "Kyogre-Primal",
    "Groudon-Primal",
    "Rattata-Alola",
    "Raticate-Alola",
    "Raichu-Alola",
    "Sandshrew-Alola",
    "Sandslash-Alola",
    "Vulpix-Alola",
    "Ninetales-Alola",
    "Diglett-Alola",
    "Dugtrio-Alola",
    "Meowth-Alola",
    "Persian-Alola",
    "Geodude-Alola",
    "Graveler-Alola",
    "Golem-Alola",
    "Grimer-Alola",
    "Muk-Alola",
    "Exeggutor-Alola",
    "Marowak-Alola",
    "Meowth-Galar",
    "Ponyta-Galar",
    "Rapidash-Galar",
    "Slowpoke-Galar",
    "Slowbro-Galar",
    "Farfetch’d-Galar",
    "Weezing-Galar",
    "Mr. Mime-Galar",
    "Articuno-Galar",
    "Zapdos-Galar",
    "Moltres-Galar",
    "Slowking-Galar",
    "Corsola-Galar",
    "Zigzagoon-Galar",
    "Linoone-Galar",
    "Darumaka-Galar",
    "Darmanitan-Galar",
    "Yamask-Galar",
    "Stunfisk-Galar",
    "Growlithe-Hisui",
    "Arcanine-Hisui",
    "Voltorb-Hisui",
    "Electrode-Hisui",
    "Typhlosion-Hisui",
    "Qwilfish-Hisui",
    "Sneasel-Hisui",
    "Samurott-Hisui",
    "Lilligant-Hisui",
    "Zorua-Hisui",
    "Zoroark-Hisui",
    "Braviary-Hisui",
    "Sliggoo-Hisui",
    "Goodra-Hisui",
    "Avalugg-Hisui",
    "Decidueye-Hisui",
    "Pikachu-Cosplay",
    "Pikachu-Rock-Star",
    "Pikachu-Belle",
    "Pikachu-Pop-Star",
    "Pikachu-PhD",
    "Pikachu-Libre",
    "Pikachu-Original",
    "Pikachu-Hoenn",
    "Pikachu-Sinnoh",
    "Pikachu-Unova",
    "Pikachu-Kalos",
    "Pikachu-Alola",
    "Pikachu-Partner",
    "Pikachu-World",
    "Pichu-Spiky-eared",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Castform-Sunny",
    "Castform-Rainy",
    "Castform-Snowy",
    "Deoxys-Attack",
    "Deoxys-Defense",
    "Deoxys-Speed",
    "Burmy",
    "Burmy",
    "Wormadam-Sandy",
    "Wormadam-Trash",
    "Cherrim-Sunshine",
    "Shellos",
    "Gastrodon",
    "Rotom-Heat",
    "Rotom-Wash",
    "Rotom-Frost",
    "Rotom-Fan",
    "Rotom-Mow",
    "Dialga-Origin",
    "Palkia-Origin",
    "Giratina-Origin",
    "Shaymin-Sky",
    "Arceus-Fighting",
    "Arceus-Flying",
    "Arceus-Poison",
    "Arceus-Ground",
    "Arceus-Rock",
    "Arceus-Bug",
    "Arceus-Ghost",
    "Arceus-Steel",
    "Arceus-Fire",
    "Arceus-Water",
    "Arceus-Grass",
    "Arceus-Electric",
    "Arceus-Psychic",
    "Arceus-Ice",
    "Arceus-Dragon",
    "Arceus-Dark",
    "Arceus-Fairy",
    "Basculin-Blue-Striped",
    "Basculin-White-Striped",
    "Darmanitan-Zen",
    "Darmanitan-Galar-Zen",
    "Deerling",
    "Deerling",
    "Deerling",
    "Sawsbuck",
    "Sawsbuck",
    "Sawsbuck",
    "Tornadus-Therian",
    "Thundurus-Therian",
    "Landorus-Therian",
    "Enamorus-Therian",
    "Kyurem-White",
    "Kyurem-Black",
    "Keldeo-Resolute",
    "Meloetta-Pirouette",
    "Genesect-Douse",
    "Genesect-Shock",
    "Genesect-Burn",
    "Genesect-Chill",
    "Greninja",
    "Greninja-Ash",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Flabébé",
    "Flabébé",
    "Flabébé",
    "Flabébé",
    "Floette",
    "Floette",
    "Floette",
    "Floette",
    "Floette-Eternal",
    "Florges",
    "Florges",
    "Florges",
    "Florges",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Meowstic-F",
    "Aegislash-Blade",
    "Pumpkaboo-Small",
    "Pumpkaboo-Large",
    "Pumpkaboo-Super",
    "Gourgeist-Small",
    "Gourgeist-Large",
    "Gourgeist-Super",
    "Xerneas",
    "Zygarde-10",
    "Zygarde-10",
    "Zygarde",
    "Zygarde-Complete",
    "Hoopa-Unbound",
    "Oricorio-Pom-Pom",
    "Oricorio-Pa'u ",
    "Oricorio-Sensu",
    "Rockruff",
    "Lycanroc-Midnight",
    "Lycanroc-Dusk",
    "Wishiwashi-School",
    "Silvally-Fighting",
    "Silvally-Flying",
    "Silvally-Poison",
    "Silvally-Ground",
    "Silvally-Rock",
    "Silvally-Bug",
    "Silvally-Ghost",
    "Silvally-Steel",
    "Silvally-Fire",
    "Silvally-Water",
    "Silvally-Grass",
    "Silvally-Electric",
    "Silvally-Psychic",
    "Silvally-Ice",
    "Silvally-Dragon",
    "Silvally-Dark",
    "Silvally-Fairy",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Mimikyu-Busted",
    "Necrozma-Dusk-Mane",
    "Necrozma-Dawn-Wings",
    "Necrozma-Ultra",
    "Magearna-Original",
    "Cramorant-Gulping",
    "Cramorant-Gorging",
    "Toxtricity-Low-Key",
    "Sinistea-Antique",
    "Polteageist-Antique",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Eiscue-Noice",
    "Indeedee-F",
    "Morpeko-Hangry",
    "Zacian-Crowned",
    "Zamazenta-Crowned",
    "Eternatus-Eternamax",
    "Urshifu-Rapid-Strike",
    "Zarude-Dada",
    "Calyrex-Ice",
    "Calyrex-Shadow"
]

ZONE_NAMES = [
    "Littleroot Town",
    "Oldale Town",
    "Dewford Town",
    "Lavaridge Town",
    "Fallarbor Town",
    "Verdanturf Town",
    "Pacifidlog Town",
    "Petalburg City",
    "Slateport City",
    "Mauville City",
    "Rustboro City",
    "Fortree City",
    "Lilycove City",
    "Mossdeep City",
    "Sootopolis City",
    "Ever Grande City",
    "Route 101",
    "Route 102",
    "Route 103",
    "Route 104",
    "Route 105",
    "Route 106",
    "Route 107",
    "Route 108",
    "Route 109",
    "Route 110",
    "Route 111",
    "Route 112",
    "Route 113",
    "Route 114",
    "Route 115",
    "Route 116",
    "Route 117",
    "Route 118",
    "Route 119",
    "Route 120",
    "Route 121",
    "Route 122",
    "Route 123",
    "Route 124",
    "Route 125",
    "Route 126",
    "Route 127",
    "Route 128",
    "Route 129",
    "Route 130",
    "Route 131",
    "Route 132",
    "Route 133",
    "Route 134",
    "Route 124 Underwater",
    "Route 126 Underwater",
    "Underwater (Route 127)",
    "Underwater (Route 128)",
    "Underwater (Sootopolis City)",
    "Granite Cave",
    "Mt. Chimney",
    "Safari Zone",
    "Battle Frontier",
    "Petalburg Woods",
    "Rusturf Tunnel",
    "Abandoned Ship",
    "New Mauville",
    "Meteor Falls",
    "Meteor Falls (unused)",
    "Mt. Pyre",
    "Hideout* (Magma HideoutR/Aqua HideoutS)",
    "Shoal Cave",
    "Seafloor Cavern",
    "Underwater (Seafloor Cavern)",
    "Victory Road",
    "Mirage Island",
    "Cave of Origin",
    "Southern Island",
    "Fiery Path",
    "Fiery Path (unused)",
    "Jagged Pass",
    "Jagged Pass (unused)",
    "Sealed Chamber",
    "Underwater (Route 134)",
    "Scorched Slab",
    "Island Cave",
    "Desert Ruins",
    "Ancient Tomb",
    "Inside of Truck",
    "Sky Pillar",
    "Secret Base",
    "Ferry",
    "Pallet Town",
    "Viridian City",
    "Pewter City",
    "Cerulean City",
    "Lavender Town",
    "Vermilion City",
    "Celadon City",
    "Fuchsia City",
    "Cinnabar Island",
    "Indigo Plateau",
    "Saffron City",
    "Route 4 (Pokémon Center)",
    "Route 10 (Pokémon Center)",
    "Route 1",
    "Route 2",
    "Route 3",
    "Route 4",
    "Route 5",
    "Route 6",
    "Route 7",
    "Route 8",
    "Route 9",
    "Route 10",
    "Route 11",
    "Route 12",
    "Route 13",
    "Route 14",
    "Route 15",
    "Route 16",
    "Route 17",
    "Route 18",
    "Route 19",
    "Route 20",
    "Route 21",
    "Route 22",
    "Route 23",
    "Route 24",
    "Route 25",
    "Viridian Forest",
    "Mt. Moon",
    "S.S. Anne",
    "Underground Path (Routes 5-6)",
    "Underground Path (Routes 7-8)",
    "Diglett's Cave",
    "Victory Road",
    "Rocket Hideout",
    "Silph Co.",
    "Pokémon Mansion",
    "Safari Zone",
    "Pokémon League",
    "Rock Tunnel",
    "Seafoam Islands",
    "Pokémon Tower",
    "Cerulean Cave",
    "Power Plant",
    "One Island",
    "Two Island",
    "Three Island",
    "Four Island",
    "Five Island",
    "Seven Island",
    "Six Island",
    "Kindle Road",
    "Treasure Beach",
    "Cape Brink",
    "Bond Bridge",
    "Three Isle Port",
    "Sevii Isle 6",
    "Sevii Isle 7",
    "Sevii Isle 8",
    "Sevii Isle 9",
    "Resort Gorgeous",
    "Water Labyrinth",
    "Five Isle Meadow",
    "Memorial Pillar",
    "Outcast Island",
    "Green Path",
    "Water Path",
    "Ruin Valley",
    "Trainer Tower (exterior)",
    "Canyon Entrance",
    "Sevault Canyon",
    "Tanoby Ruins",
    "Sevii Isle 22",
    "Sevii Isle 23",
    "Sevii Isle 24",
    "Navel Rock",
    "Mt. Ember",
    "Berry Forest",
    "Icefall Cave",
    "Rocket Warehouse",
    "Trainer Tower",
    "Dotted Hole",
    "Lost Cave",
    "Pattern Bush",
    "Altering Cave",
    "Tanoby Chambers",
    "Three Isle Path",
    "Tanoby Key",
    "Birth Island",
    "Monean Chamber",
    "Liptoo Chamber",
    "Weepth Chamber",
    "Dilford Chamber",
    "Scufib Chamber",
    "Rixy Chamber",
    "Viapois Chamber",
    "Ember Spa",
    "Special Area",
    "Aqua Hideout",
    "Magma Hideout",
    "Mirage Tower",
    "Birth Island",
    "Faraway Island",
    "Artisan Cave",
    "Marine Cave",
    "Underwater (Marine Cave)",
    "Terra Cave",
    "Underwater (Route 105)",
    "Underwater (Route 125)",
    "Underwater (Route 129)",
    "Desert Underpass",
    "Altering Cave",
    "Navel Rock",
    "Trainer Hill",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Gift Egg",
    "In-game Trade",
    "Fateful Encounter"
]

FULLDATA_ZONE = {
    "Starter": None,
	"Littleroot Town": None,
	"Route 101": None,
	"Oldale Town": None,
	"Route 103": None,
	"Route 102": None,
	"Petalburg City": None,
	"Route 104": None,
	"Dewford Town": None,
	"Route 107": None,
	"Route 106": None,
	"Granite Cave": None,
	"Route 109": None,
	"Slateport City": None,
	"Route 110": None,
	"Petalburg Woods": None,
	"Rustboro City": None,
	"Route 115": None,
	"Route 116": None,
	"Rusturf Tunnel": None,
	"Verdanturf Town": None,
	"Route 117": None,
    "Mauville City": None,
	"Route 111": None,
	"Route 118": None,
	"Altering Cave": None,
	"Mirage Tower": None,
	"Route 113": None,
	"Fallarbor Town": None,
	"Desert Underpass": None,
	"Route 114": None,
	"Meteor Falls": None,
	"Route 112": None,
	"Fiery Path": None,
	"Mt. Chimney": None,
	"Jagged Pass": None,
    "Lavaridge Town": None,
	"Route 134": None,
	"New Mauville": None,
	"Route 105": None,
	"Route 108": None,
	"Abandoned Ship": None,
	"Route 119": None,
	"Fortree City": None,
	"Route 120": None,
	"Scorched Slab": None,
	"Route 121": None,
	"Safari Zone": None,
	"Lilycove City": None,
	"Route 122": None,
	"Route 123": None,
	"Mt. Pyre": None,
	"Magma Hideout": None,
	"Aqua Hideout": None,
	"Route 124": None,
	"Mossdeep City": None,
	"Route 125": None,
	"Shoal Cave": None,
	"Route 127": None,
    "Route 124 Underwater": None,
	"Route 126": None,
    "Route 126 Underwater": None,
	"Sootopolis City": None,
	"Route 128": None,
	"Route 129": None,
	"Ever Grande City": None,
	"Seafloor Cavern": None,
	"Cave of Origin": None,
	"Route 130": None,
	"Route 131": None,
	"Pacifidlog Town": None,
	"Route 132": None,
	"Route 133": None,
	"Sky Pillar": None,
	"Victory Road": None
}

ZONE_ORDER = list(FULLDATA_ZONE.keys())