import os

POKEMON_LIST  = [None,
"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran-F",
"Nidorina",
"Nidoqueen",
"Nidoran-M",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch’d",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr. Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
"Chikorita",
"Bayleef",
"Meganium",
"Cyndaquil",
"Quilava",
"Typhlosion",
"Totodile",
"Croconaw",
"Feraligatr",
"Sentret",
"Furret",
"Hoothoot",
"Noctowl",
"Ledyba",
"Ledian",
"Spinarak",
"Ariados",
"Crobat",
"Chinchou",
"Lanturn",
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Togetic",
"Natu",
"Xatu",
"Mareep",
"Flaaffy",
"Ampharos",
"Bellossom",
"Marill",
"Azumarill",
"Sudowoodo",
"Politoed",
"Hoppip",
"Skiploom",
"Jumpluff",
"Aipom",
"Sunkern",
"Sunflora",
"Yanma",
"Wooper",
"Quagsire",
"Espeon",
"Umbreon",
"Murkrow",
"Slowking",
"Misdreavus",
"Unown",
"Wobbuffet",
"Girafarig",
"Pineco",
"Forretress",
"Dunsparce",
"Gligar",
"Steelix",
"Snubbull",
"Granbull",
"Qwilfish",
"Scizor",
"Shuckle",
"Heracross",
"Sneasel",
"Teddiursa",
"Ursaring",
"Slugma",
"Magcargo",
"Swinub",
"Piloswine",
"Corsola",
"Remoraid",
"Octillery",
"Delibird",
"Mantine",
"Skarmory",
"Houndour",
"Houndoom",
"Kingdra",
"Phanpy",
"Donphan",
"Porygon2",
"Stantler",
"Smeargle",
"Tyrogue",
"Hitmontop",
"Smoochum",
"Elekid",
"Magby",
"Miltank",
"Blissey",
"Raikou",
"Entei",
"Suicune",
"Larvitar",
"Pupitar",
"Tyranitar",
"Lugia",
"Ho-Oh",
"Celebi",
"Treecko",
"Grovyle",
"Sceptile",
"Torchic",
"Combusken",
"Blaziken",
"Mudkip",
"Marshtomp",
"Swampert",
"Poochyena",
"Mightyena",
"Zigzagoon",
"Linoone",
"Wurmple",
"Silcoon",
"Beautifly",
"Cascoon",
"Dustox",
"Lotad",
"Lombre",
"Ludicolo",
"Seedot",
"Nuzleaf",
"Shiftry",
"Taillow",
"Swellow",
"Wingull",
"Pelipper",
"Ralts",
"Kirlia",
"Gardevoir",
"Surskit",
"Masquerain",
"Shroomish",
"Breloom",
"Slakoth",
"Vigoroth",
"Slaking",
"Nincada",
"Ninjask",
"Shedinja",
"Whismur",
"Loudred",
"Exploud",
"Makuhita",
"Hariyama",
"Azurill",
"Nosepass",
"Skitty",
"Delcatty",
"Sableye",
"Mawile",
"Aron",
"Lairon",
"Aggron",
"Meditite",
"Medicham",
"Electrike",
"Manectric",
"Plusle",
"Minun",
"Volbeat",
"Illumise",
"Roselia",
"Gulpin",
"Swalot",
"Carvanha",
"Sharpedo",
"Wailmer",
"Wailord",
"Numel",
"Camerupt",
"Torkoal",
"Spoink",
"Grumpig",
"Spinda",
"Trapinch",
"Vibrava",
"Flygon",
"Cacnea",
"Cacturne",
"Swablu",
"Altaria",
"Zangoose",
"Seviper",
"Lunatone",
"Solrock",
"Barboach",
"Whiscash",
"Corphish",
"Crawdaunt",
"Baltoy",
"Claydol",
"Lileep",
"Cradily",
"Anorith",
"Armaldo",
"Feebas",
"Milotic",
"Castform",
"Kecleon",
"Shuppet",
"Banette",
"Duskull",
"Dusclops",
"Tropius",
"Chimecho",
"Absol",
"Wynaut",
"Snorunt",
"Glalie",
"Spheal",
"Sealeo",
"Walrein",
"Clamperl",
"Huntail",
"Gorebyss",
"Relicanth",
"Luvdisc",
"Bagon",
"Shelgon",
"Salamence",
"Beldum",
"Metang",
"Metagross",
"Regirock",
"Regice",
"Registeel",
"Latias",
"Latios",
"Kyogre",
"Groudon",
"Rayquaza",
"Jirachi",
"Deoxys",
"Turtwig",
"Grotle",
"Torterra",
"Chimchar",
"Monferno",
"Infernape",
"Piplup",
"Prinplup",
"Empoleon",
"Starly",
"Staravia",
"Staraptor",
"Bidoof",
"Bibarel",
"Kricketot",
"Kricketune",
"Shinx",
"Luxio",
"Luxray",
"Budew",
"Roserade",
"Cranidos",
"Rampardos",
"Shieldon",
"Bastiodon",
"Burmy",
"Wormadam",
"Mothim",
"Combee",
"Vespiquen",
"Pachirisu",
"Buizel",
"Floatzel",
"Cherubi",
"Cherrim",
"Shellos",
"Gastrodon",
"Ambipom",
"Drifloon",
"Drifblim",
"Buneary",
"Lopunny",
"Mismagius",
"Honchkrow",
"Glameow",
"Purugly",
"Chingling",
"Stunky",
"Skuntank",
"Bronzor",
"Bronzong",
"Bonsly",
"Mime Jr.",
"Happiny",
"Chatot",
"Spiritomb",
"Gible",
"Gabite",
"Garchomp",
"Munchlax",
"Riolu",
"Lucario",
"Hippopotas",
"Hippowdon",
"Skorupi",
"Drapion",
"Croagunk",
"Toxicroak",
"Carnivine",
"Finneon",
"Lumineon",
"Mantyke",
"Snover",
"Abomasnow",
"Weavile",
"Magnezone",
"Lickilicky",
"Rhyperior",
"Tangrowth",
"Electivire",
"Magmortar",
"Togekiss",
"Yanmega",
"Leafeon",
"Glaceon",
"Gliscor",
"Mamoswine",
"Porygon-Z",
"Gallade",
"Probopass",
"Dusknoir",
"Froslass",
"Rotom",
"Uxie",
"Mesprit",
"Azelf",
"Dialga",
"Palkia",
"Heatran",
"Regigigas",
"Giratina",
"Cresselia",
"Phione",
"Manaphy",
"Darkrai",
"Shaymin",
"Arceus",
"Victini",
"Snivy",
"Servine",
"Serperior",
"Tepig",
"Pignite",
"Emboar",
"Oshawott",
"Dewott",
"Samurott",
"Patrat",
"Watchog",
"Lillipup",
"Herdier",
"Stoutland",
"Purrloin",
"Liepard",
"Pansage",
"Simisage",
"Pansear",
"Simisear",
"Panpour",
"Simipour",
"Munna",
"Musharna",
"Pidove",
"Tranquill",
"Unfezant",
"Blitzle",
"Zebstrika",
"Roggenrola",
"Boldore",
"Gigalith",
"Woobat",
"Swoobat",
"Drilbur",
"Excadrill",
"Audino",
"Timburr",
"Gurdurr",
"Conkeldurr",
"Tympole",
"Palpitoad",
"Seismitoad",
"Throh",
"Sawk",
"Sewaddle",
"Swadloon",
"Leavanny",
"Venipede",
"Whirlipede",
"Scolipede",
"Cottonee",
"Whimsicott",
"Petilil",
"Lilligant",
"Basculin",
"Sandile",
"Krokorok",
"Krookodile",
"Darumaka",
"Darmanitan",
"Maractus",
"Dwebble",
"Crustle",
"Scraggy",
"Scrafty",
"Sigilyph",
"Yamask",
"Cofagrigus",
"Tirtouga",
"Carracosta",
"Archen",
"Archeops",
"Trubbish",
"Garbodor",
"Zorua",
"Zoroark",
"Minccino",
"Cinccino",
"Gothita",
"Gothorita",
"Gothitelle",
"Solosis",
"Duosion",
"Reuniclus",
"Ducklett",
"Swanna",
"Vanillite",
"Vanillish",
"Vanilluxe",
"Deerling",
"Sawsbuck",
"Emolga",
"Karrablast",
"Escavalier",
"Foongus",
"Amoonguss",
"Frillish",
"Jellicent",
"Alomomola",
"Joltik",
"Galvantula",
"Ferroseed",
"Ferrothorn",
"Klink",
"Klang",
"Klinklang",
"Tynamo",
"Eelektrik",
"Eelektross",
"Elgyem",
"Beheeyem",
"Litwick",
"Lampent",
"Chandelure",
"Axew",
"Fraxure",
"Haxorus",
"Cubchoo",
"Beartic",
"Cryogonal",
"Shelmet",
"Accelgor",
"Stunfisk",
"Mienfoo",
"Mienshao",
"Druddigon",
"Golett",
"Golurk",
"Pawniard",
"Bisharp",
"Bouffalant",
"Rufflet",
"Braviary",
"Vullaby",
"Mandibuzz",
"Heatmor",
"Durant",
"Deino",
"Zweilous",
"Hydreigon",
"Larvesta",
"Volcarona",
"Cobalion",
"Terrakion",
"Virizion",
"Tornadus",
"Thundurus",
"Reshiram",
"Zekrom",
"Landorus",
"Kyurem",
"Keldeo",
"Meloetta",
"Genesect",
"Chespin",
"Quilladin",
"Chesnaught",
"Fennekin",
"Braixen",
"Delphox",
"Froakie",
"Frogadier",
"Greninja",
"Bunnelby",
"Diggersby",
"Fletchling",
"Fletchinder",
"Talonflame",
"Scatterbug",
"Spewpa",
"Vivillon",
"Litleo",
"Pyroar",
"Flabébé",
"Floette",
"Florges",
"Skiddo",
"Gogoat",
"Pancham",
"Pangoro",
"Furfrou",
"Espurr",
"Meowstic",
"Honedge",
"Doublade",
"Aegislash",
"Spritzee",
"Aromatisse",
"Swirlix",
"Slurpuff",
"Inkay",
"Malamar",
"Binacle",
"Barbaracle",
"Skrelp",
"Dragalge",
"Clauncher",
"Clawitzer",
"Helioptile",
"Heliolisk",
"Tyrunt",
"Tyrantrum",
"Amaura",
"Aurorus",
"Sylveon",
"Hawlucha",
"Dedenne",
"Carbink",
"Goomy",
"Sliggoo",
"Goodra",
"Klefki",
"Phantump",
"Trevenant",
"Pumpkaboo",
"Gourgeist",
"Bergmite",
"Avalugg",
"Noibat",
"Noivern",
"Xerneas",
"Yveltal",
"Zygarde",
"Diancie",
"Hoopa",
"Volcanion",
"Rowlet",
"Dartrix",
"Decidueye",
"Litten",
"Torracat",
"Incineroar",
"Popplio",
"Brionne",
"Primarina",
"Pikipek",
"Trumbeak",
"Toucannon",
"Yungoos",
"Gumshoos",
"Grubbin",
"Charjabug",
"Vikavolt",
"Crabrawler",
"Crabominable",
"Oricorio",
"Cutiefly",
"Ribombee",
"Rockruff",
"Lycanroc",
"Wishiwashi",
"Mareanie",
"Toxapex",
"Mudbray",
"Mudsdale",
"Dewpider",
"Araquanid",
"Fomantis",
"Lurantis",
"Morelull",
"Shiinotic",
"Salandit",
"Salazzle",
"Stufful",
"Bewear",
"Bounsweet",
"Steenee",
"Tsareena",
"Comfey",
"Oranguru",
"Passimian",
"Wimpod",
"Golisopod",
"Sandygast",
"Palossand",
"Pyukumuku",
"Type: Null",
"Silvally",
"Minior",
"Komala",
"Turtonator",
"Togedemaru",
"Mimikyu",
"Bruxish",
"Drampa",
"Dhelmise",
"Jangmo-o",
"Hakamo-o",
"Kommo-o",
"Tapu Koko",
"Tapu Lele",
"Tapu Bulu",
"Tapu Fini",
"Cosmog",
"Cosmoem",
"Solgaleo",
"Lunala",
"Nihilego",
"Buzzwole",
"Pheromosa",
"Xurkitree",
"Celesteela",
"Kartana",
"Guzzlord",
"Necrozma",
"Magearna",
"Marshadow",
"Poipole",
"Naganadel",
"Stakataka",
"Blacephalon",
"Zeraora",
"Meltan",
"Melmetal",
"Grookey",
"Thwackey",
"Rillaboom",
"Scorbunny",
"Raboot",
"Cinderace",
"Sobble",
"Drizzile",
"Inteleon",
"Skwovet",
"Greedent",
"Rookidee",
"Corvisquire",
"Corviknight",
"Blipbug",
"Dottler",
"Orbeetle",
"Nickit",
"Thievul",
"Gossifleur",
"Eldegoss",
"Wooloo",
"Dubwool",
"Chewtle",
"Drednaw",
"Yamper",
"Boltund",
"Rolycoly",
"Carkol",
"Coalossal",
"Applin",
"Flapple",
"Appletun",
"Silicobra",
"Sandaconda",
"Cramorant",
"Arrokuda",
"Barraskewda",
"Toxel",
"Toxtricity",
"Sizzlipede",
"Centiskorch",
"Clobbopus",
"Grapploct",
"Sinistea",
"Polteageist",
"Hatenna",
"Hattrem",
"Hatterene",
"Impidimp",
"Morgrem",
"Grimmsnarl",
"Obstagoon",
"Perrserker",
"Cursola",
"Sirfetch’d",
"Mr. Rime",
"Runerigus",
"Milcery",
"Alcremie",
"Falinks",
"Pincurchin",
"Snom",
"Frosmoth",
"Stonjourner",
"Eiscue",
"Indeedee",
"Morpeko",
"Cufant",
"Copperajah",
"Dracozolt",
"Arctozolt",
"Dracovish",
"Arctovish",
"Duraludon",
"Dreepy",
"Drakloak",
"Dragapult",
"Zacian",
"Zamazenta",
"Eternatus",
"Kubfu",
"Urshifu",
"Zarude",
"Regieleki",
"Regidrago",
"Glastrier",
"Spectrier",
"Calyrex",
"Wyrdeer",
"Kleavor",
"Ursaluna",
"Basculegion",
"Sneasler",
"Overqwil",
"Enamorus",
"Venusaur-Mega",
"Charizard-Mega-X",
"Charizard-Mega-Y",
"Blastoise-Mega",
"Beedrill-Mega",
"Pidgeot-Mega",
"Alakazam-Mega",
"Slowbro-Mega",
"Gengar-Mega",
"Kangaskhan-Mega",
"Pinsir-Mega",
"Gyarados-Mega",
"Aerodactyl-Mega",
"Mewtwo-Mega-X",
"Mewtwo-Mega-Y",
"Ampharos-Mega",
"Steelix-Mega",
"Scizor-Mega",
"Heracross-Mega",
"Houndoom-Mega",
"Tyranitar-Mega",
"Sceptile-Mega",
"Blaziken-Mega",
"Swampert-Mega",
"Gardevoir-Mega",
"Sableye-Mega",
"Mawile-Mega",
"Aggron-Mega",
"Medicham-Mega",
"Manectric-Mega",
"Sharpedo-Mega",
"Camerupt-Mega",
"Altaria-Mega",
"Banette-Mega",
"Absol-Mega",
"Glalie-Mega",
"Salamence-Mega",
"Metagross-Mega",
"Latias-Mega",
"Latios-Mega",
"Lopunny-Mega",
"Garchomp-Mega",
"Lucario-Mega",
"Abomasnow-Mega",
"Gallade-Mega",
"Audino-Mega",
"Diancie-Mega",
"Rayquaza-Mega",
"Kyogre-Primal",
"Groudon-Primal",
"Rattata-Alola",
"Raticate-Alola",
"Raichu-Alola",
"Sandshrew-Alola",
"Sandslash-Alola",
"Vulpix-Alola",
"Ninetales-Alola",
"Diglett-Alola",
"Dugtrio-Alola",
"Meowth-Alola",
"Persian-Alola",
"Geodude-Alola",
"Graveler-Alola",
"Golem-Alola",
"Grimer-Alola",
"Muk-Alola",
"Exeggutor-Alola",
"Marowak-Alola",
"Meowth-Galar",
"Ponyta-Galar",
"Rapidash-Galar",
"Slowpoke-Galar",
"Slowbro-Galar",
"Farfetch’d-Galar",
"Weezing-Galar",
"Mr. Mime-Galar",
"Articuno-Galar",
"Zapdos-Galar",
"Moltres-Galar",
"Slowking-Galar",
"Corsola-Galar",
"Zigzagoon-Galar",
"Linoone-Galar",
"Darumaka-Galar",
"Darmanitan-Galar",
"Yamask-Galar",
"Stunfisk-Galar",
"Growlithe-Hisui",
"Arcanine-Hisui",
"Voltorb-Hisui",
"Electrode-Hisui",
"Typhlosion-Hisui",
"Qwilfish-Hisui",
"Sneasel-Hisui",
"Samurott-Hisui",
"Lilligant-Hisui",
"Zorua-Hisui",
"Zoroark-Hisui",
"Braviary-Hisui",
"Sliggoo-Hisui",
"Goodra-Hisui",
"Avalugg-Hisui",
"Decidueye-Hisui",
"Pikachu-Cosplay",
"Pikachu-Rock-Star",
"Pikachu-Belle",
"Pikachu-Pop-Star",
"Pikachu-PhD",
"Pikachu-Libre",
"Pikachu-Original",
"Pikachu-Hoenn",
"Pikachu-Sinnoh",
"Pikachu-Unova",
"Pikachu-Kalos",
"Pikachu-Alola",
"Pikachu-Partner",
"Pikachu-World",
"Pichu-Spiky-eared",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Castform-Sunny",
"Castform-Rainy",
"Castform-Snowy",
"Deoxys-Attack",
"Deoxys-Defense",
"Deoxys-Speed",
"Burmy",
"Burmy",
"Wormadam-Sandy",
"Wormadam-Trash",
"Cherrim-Sunshine",
"Shellos",
"Gastrodon",
"Rotom-Heat",
"Rotom-Wash",
"Rotom-Frost",
"Rotom-Fan",
"Rotom-Mow",
"Dialga-Origin",
"Palkia-Origin",
"Giratina-Origin",
"Shaymin-Sky",
"Arceus-Fighting",
"Arceus-Flying",
"Arceus-Poison",
"Arceus-Ground",
"Arceus-Rock",
"Arceus-Bug",
"Arceus-Ghost",
"Arceus-Steel",
"Arceus-Fire",
"Arceus-Water",
"Arceus-Grass",
"Arceus-Electric",
"Arceus-Psychic",
"Arceus-Ice",
"Arceus-Dragon",
"Arceus-Dark",
"Arceus-Fairy",
"Basculin-Blue-Striped",
"Basculin-White-Striped",
"Darmanitan-Zen",
"Darmanitan-Galar-Zen",
"Deerling",
"Deerling",
"Deerling",
"Sawsbuck",
"Sawsbuck",
"Sawsbuck",
"Tornadus-Therian",
"Thundurus-Therian",
"Landorus-Therian",
"Enamorus-T",
"Kyurem-White",
"Kyurem-Black",
"Keldeo-Resolute",
"Meloetta-Pirouette",
"Genesect-Douse",
"Genesect-Shock",
"Genesect-Burn",
"Genesect-Chill",
"Greninja",
"Greninja-Ash",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Flabébé",
"Flabébé",
"Flabébé",
"Flabébé",
"Floette",
"Floette",
"Floette",
"Floette",
"Floette-Eternal",
"Florges",
"Florges",
"Florges",
"Florges",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Meowstic-F",
"Aegislash-Blade",
"Pumpkaboo-Small",
"Pumpkaboo-Large",
"Pumpkaboo-Super",
"Gourgeist-Small",
"Gourgeist-Large",
"Gourgeist-Super",
"Xerneas",
"Zygarde-10%",
"Zygarde-10%",
"Zygarde",
"Zygarde-Complete",
"Hoopa-Unbound",
"Oricorio-Pom-Pom",
"Oricorio-Pa'u",
"Oricorio-Sensu",
"Rockruff",
"Lycanroc-Midnight",
"Lycanroc-Dusk",
"Wishiwashi-School",
"Silvally-Fighting",
"Silvally-Flying",
"Silvally-Poison",
"Silvally-Ground",
"Silvally-Rock",
"Silvally-Bug",
"Silvally-Ghost",
"Silvally-Steel",
"Silvally-Fire",
"Silvally-Water",
"Silvally-Grass",
"Silvally-Electric",
"Silvally-Psychic",
"Silvally-Ice",
"Silvally-Dragon",
"Silvally-Dark",
"Silvally-Fairy",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Mimikyu-Busted",
"Necrozma-Dusk-Mane",
"Necrozma-Dawn-Wings",
"Necrozma-Ultra",
"Magearna-Original",
"Cramorant-Gulping",
"Cramorant-Gorging",
"Toxtricity-Low-Key",
"Sinistea-Antique",
"Polteageist-Antique",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Eiscue-Noice",
"Indeedee-F",
"Morpeko-Hangry",
"Zacian-Crowned",
"Zamazenta-Crowned",
"Eternatus-Eternamax",
"Urshifu-Rapid-Strike",
"Zarude-Dada",
"Calyrex-Ice",
"Calyrex-Shadow"
]
ITEM_LIST = [None,
"Poke Ball",
"Great Ball",
"Ultra Ball",
"Master Ball",
"Premier Ball",
"Heal Ball",
"Net Ball",
"Nest Ball",
"Dive Ball",
"Dusk Ball",
"Timer Ball",
"Quick Ball",
"Repeat Ball",
"Luxury Ball",
"Level Ball",
"Lure Ball",
"Moon Ball",
"Friend Ball",
"Love Ball",
"Fast Ball",
"Heavy Ball",
"Dream Ball",
"Safari Ball",
"Sport Ball",
"Park Ball",
"Beast Ball",
"Cherish Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Berry Juice",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Bottle Cap",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Rare Bone",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Helix Fossil",
"Dome Fossil",
"Old Amber",
"Root Fossil",
"Claw Fossil",
"Armor Fossil",
"Skull Fossil",
"Cover Fossil",
"Plume Fossil",
"Jaw Fossil",
"Sail Fossil",
"Fossilized Bird",
"Fossilized Fish",
"Fossilized Drake",
"Fossilized Dino",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Mail",
"Fire Stone",
"Water Stone",
"Thunder Stone",
"Leaf Stone",
"Ice Stone",
"Sun Stone",
"Moon Stone",
"Shiny Stone",
"Dusk Stone",
"Dawn Stone",
"Sweet Apple",
"Tart Apple",
"Cracked Pot",
"Chipped Pot",
"Galarica Cuff",
"Galarica Wreath",
"Dragon Scale",
"Up-Grade",
"Protector",
"Electirizer",
"Magmarizer",
"Dubious Disc",
"Reaper Cloth",
"Prism Scale",
"Whipped Dream",
"Sachet",
"Oval Stone",
"Strawberry Sweet",
"Love Sweet",
"Berry Sweet",
"Clover Sweet",
"Flower Sweet",
"Star Sweet",
"Ribbon Sweet",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Flame Plate",
"Splash Plate",
"Zap Plate",
"Meadow Plate",
"Icicle Plate",
"Fist Plate",
"Toxic Plate",
"Earth Plate",
"Sky Plate",
"Mind Plate",
"Insect Plate",
"Stone Plate",
"Spooky Plate",
"Draco Plate",
"Dread Plate",
"Iron Plate",
"Pixie Plate",
"Douse Drive",
"Shock Drive",
"Burn Drive",
"Chill Drive",
"Fire Memory",
"Water Memory",
"Electric Memory",
"Grass Memory",
"Ice Memory",
"Fighting Memory",
"Poison Memory",
"Ground Memory",
"Flying Memory",
"Psychic Memory",
"Bug Memory",
"Rock Memory",
"Ghost Memory",
"Dragon Memory",
"Dark Memory",
"Steel Memory",
"Fairy Memory",
"Rusted Sword",
"Rusted Shield",
"Red Orb",
"Blue Orb",
"Venusaurite",
"Charizardite X",
"Charizardite Y",
"Blastoisinite",
"Beedrillite",
"Pidgeotite",
"Alakazite",
"Slowbronite",
"Gengarite",
"Kangaskhanite",
"Pinsirite",
"Gyaradosite",
"Aerodactylite",
"Mewtwonite X",
"Mewtwonite Y",
"Ampharosite",
"Steelixite",
"Scizorite",
"Heracronite",
"Houndoominite",
"Tyranitarite",
"Sceptilite",
"Blazikenite",
"Swampertite",
"Gardevoirite",
"Sablenite",
"Mawilite",
"Aggronite",
"Medichamite",
"Manectite",
"Sharpedonite",
"Cameruptite",
"Altarianite",
"Banettite",
"Absolite",
"Glalitite",
"Salamencite",
"Metagrossite",
"Latiasite",
"Latiosite",
"Lopunnite",
"Garchompite",
"Lucarionite",
"Abomasite",
"Galladite",
"Audinite",
"Diancite",
"Normal Gem",
"Fire Gem",
"Water Gem",
"Electric Gem",
"Grass Gem",
"Ice Gem",
"Fighting Gem",
"Poison Gem",
"Ground Gem",
"Flying Gem",
"Psychic Gem",
"Bug Gem",
"Rock Gem",
"Ghost Gem",
"Dragon Gem",
"Dark Gem",
"Steel Gem",
"Fairy Gem",
"Normalium Z",
"Firium Z",
"Waterium Z",
"Electrium Z",
"Grassium Z",
"Icium Z",
"Fightinium Z",
"Poisonium Z",
"Groundium Z",
"Flyinium Z",
"Psychium Z",
"Buginium Z",
"Rockium Z",
"Ghostium Z",
"Dragonium Z",
"Darkinium Z",
"Steelium Z",
"Fairium Z",
"Pikanium Z",
"Eevium Z",
"Snorlium Z",
"Mewnium Z",
"Decidium Z",
"Incinium Z",
"Primarium Z",
"Lycanium Z",
"Mimikium Z",
"Kommonium Z",
"Tapunium Z",
"Solganium Z",
"Lunalium Z",
"Marshadium Z",
"Aloraichium Z",
"Pikashunium Z",
"Ultranecrozium Z",
"Light Ball",
"Leek",
"Thick Club",
"Lucky Punch",
"Metal Powder",
"Quick Powder",
"Deep Sea Scale",
"Deep Sea Tooth",
"Soul Dew",
"Adamant Orb",
"Lustrous Orb",
"Griseous Orb",
"Sea Incense",
"Lax Incense",
"Odd Incense",
"Rock Incense",
"Full Incense",
"Wave Incense",
"Rose Incense",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Macho Brace",
"Power Weight",
"Power Bracer",
"Power Belt",
"Power Lens",
"Power Band",
"Power Anklet",
"Silk Scarf",
"Charcoal",
"Mystic Water",
"Magnet",
"Miracle Seed",
"Never-Melt Ice",
"Black Belt",
"Poison Barb",
"Soft Sand",
"Sharp Beak",
"Twisted Spoon",
"Silver Powder",
"Hard Stone",
"Spell Tag",
"Dragon Fang",
"Black Glasses",
"Metal Coat",
"Choice Band",
"Choice Specs",
"Choice Scarf",
"Flame Orb",
"Toxic Orb",
"Damp Rock",
"Heat Rock",
"Smooth Rock",
"Icy Rock",
"Electric Seed",
"Psychic Seed",
"Misty Seed",
"Grassy Seed",
"Absorb Bulb",
"Cell Battery",
"Luminous Moss",
"Snowball",
"Bright Powder",
"White Herb",
"Poke Ball",
"Quick Claw",
"Poke Ball",
"Mental Herb",
"King's Rock",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Focus Band",
"Poke Ball",
"Scope Lens",
"Leftovers",
"Shell Bell",
"Wide Lens",
"Muscle Band",
"Wise Glasses",
"Expert Belt",
"Light Clay",
"Life Orb",
"Power Herb",
"Focus Sash",
"Zoom Lens",
"Metronome",
"Iron Ball",
"Lagging Tail",
"Destiny Knot",
"Black Sludge",
"Grip Claw",
"Sticky Barb",
"Shed Shell",
"Big Root",
"Razor Claw",
"Razor Fang",
"Eviolite",
"Float Stone",
"Rocky Helmet",
"Air Balloon",
"Red Card",
"Ring Target",
"Binding Band",
"Eject Button",
"Weakness Policy",
"Assault Vest",
"Safety Goggles",
"Adrenaline Orb",
"Terrain Extender",
"Protective Pads",
"Throat Spray",
"Eject Pack",
"Heavy-Duty Boots",
"Blunder Policy",
"Room Service",
"Utility Umbrella",
"Cheri Berry",
"Chesto Berry",
"Pecha Berry",
"Rawst Berry",
"Aspear Berry",
"Leppa Berry",
"Oran Berry",
"Persim Berry",
"Lum Berry",
"Sitrus Berry",
"Figy Berry",
"Wiki Berry",
"Mago Berry",
"Aguav Berry",
"Iapapa Berry",
"Razz Berry",
"Bluk Berry",
"Nanab Berry",
"Wepear Berry",
"Pinap Berry",
"Pomeg Berry",
"Kelpsy Berry",
"Qualot Berry",
"Hondew Berry",
"Grepa Berry",
"Tamato Berry",
"Cornn Berry",
"Magost Berry",
"Rabuta Berry",
"Nomel Berry",
"Spelon Berry",
"Pamtre Berry",
"Watmel Berry",
"Durin Berry",
"Belue Berry",
"Chilan Berry",
"Occa Berry",
"Passho Berry",
"Wacan Berry",
"Rindo Berry",
"Yache Berry",
"Chople Berry",
"Kebia Berry",
"Shuca Berry",
"Coba Berry",
"Payapa Berry",
"Tanga Berry",
"Charti Berry",
"Kasib Berry",
"Haban Berry",
"Colbur Berry",
"Babiri Berry",
"Roseli Berry",
"Liechi Berry",
"Ganlon Berry",
"Salac Berry",
"Petaya Berry",
"Apicot Berry",
"Lansat Berry",
"Starf Berry",
"Enigma Berry",
"Micle Berry",
"Custap Berry",
"Jaboca Berry",
"Rowap Berry",
"Kee Berry",
"Maranga Berry",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
"Poke Ball",
]

SPRITE_FOLDER = "sprites"
POKEMONSPRITE_FOLDER = SPRITE_FOLDER + "/pokemon"
ITEMSPRITE_FOLDER = SPRITE_FOLDER + "/items"

class TrainerData:
    def __init__(self, name, zone, address, valueWhenNotBeaten, valueWhenBeaten, pokemonTeam, itemList, spriteName):
        self.name = name
        self.zone = zone
        self.address = address
        self.bitNumber = self.getBitNumber(valueWhenNotBeaten, valueWhenBeaten)
        self.pokemonTeam = pokemonTeam
        self.itemList = itemList
        self.spriteName = spriteName

    def getBitNumber(self, previousValue, currentValue):
        if not isPowerOfTwo(currentValue - previousValue):
            print("Error with trainer " + self.name + " - " + str(previousValue) + "/" + str(currentValue))
            return None
        return (currentValue - previousValue).bit_length() - 1
    
    def __str__(self):
        return f'TrainerData("{self.name}", "{self.zone}", {self.address:#010X}, {self.bitNumber}, [{",".join(str(pokedexId) for pokedexId in self.pokemonTeam)}], [{",".join(str(itemId) for itemId in self.itemList)}], "{self.spriteName}")'


def itemNameToId(name):
    if not name: 
        return None
    try:
        itemId = ITEM_LIST.index(name)
        if not os.path.isfile(f"{ITEMSPRITE_FOLDER}/{itemId}.png"):
            print(f"Item {name} ({itemId}) does not have a sprite")
        return itemId
    
    except ValueError:
        print(f"Unknown Item name: {name}")
        return name

def pokemonNameToId(name):
    if not name: 
        return None
    try:
        pokedexId = POKEMON_LIST.index(name)
        if not os.path.isfile(f"{POKEMONSPRITE_FOLDER}/{pokedexId}.png"):
            print(f"Pokemon {name} ({pokedexId}) does not have a sprite")
        return pokedexId
    
    except ValueError:
        print(f"Unknown Pokémon name: {name}")
        return name

def parseTrainerFile(filepath):
    trainers = []
    with open(filepath, encoding="utf-8") as f:
        lines = [line.rstrip("\n") for line in f if line.strip()]

    for i in range(0, len(lines), 4):  # every trainer = 4 lines
        # Line 1: trainer name
        name, zone = lines[i].strip().split("\t")

        # Line 2: address + values
        _, addr, values = lines[i+1].split("\t", 2)
        firstValue, secondValue = values.split(" -> ")
        address = int(addr, 16)  # hex string to int

        # Line 3: pokémon + sprite
        parts = lines[i+2][1:].rstrip("\t").split("\t")
        pokemonNames = parts[:-1]   # first 6 tabs
        spriteName = parts[-1]
        pokemonTeam = [pokemonNameToId(p) if p else None for p in pokemonNames]

        while pokemonTeam[-1] is None:
            pokemonTeam.pop()

        # Line 4: items + sprite
        itemNames = lines[i+3][1:].rstrip("\t").split("\t")
        itemList = [itemNameToId(i) if i else None for i in itemNames]

        trainer = TrainerData(name, zone, address, int(firstValue, 16), int(secondValue, 16), pokemonTeam, itemList, spriteName)
        print(trainer)
        trainers.append(trainer)

    return trainers

def isPowerOfTwo(x):
    return x > 0 and (x & (x - 1)) == 0

parseTrainerFile("trainersData.txt")